on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: tomhv/workflows
        path: workflow
        sparse-checkout: |
          gherkin

    - uses: actions/checkout@v4
      with:
        path: repo
        sparse-checkout: |
          features
      
    - name: Says Hello
      run: echo Hello

    - name: List feature files
      run: ls -la features
      
    - name: List workflow files
      run: ls -la workflow
      
    - name: Run script
      run: bash ./workflow/script.sh
