on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: tomhv/workflows
        path: workflow
        sparse-checkout: |
          gherkin

    - uses: actions/checkout@v4
      with:
        path: features
        sparse-checkout: |
          features
      
    - name: Says Hello
      run: echo Hello

    - name: List files
      run: ls -laR
