on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: tomhv/workflows
      
    - name: Says Hello
      run: echo Hello

    - name: List files
      run: ls -la
